server:
  port: 8080

spring:
  application:
    name: callifactory-server
  datasource:
    url: jdbc:mysql://localhost:3306/study?createDatabaseIfNotExist=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialization-fail-timeout: -1
  sql:
    init:
      mode: always
